<?php

declare(strict_types=1);

namespace Modules\Tournaments\Tests\Integration\Infrastructure\Persistence\Eloquent\Repositories;

use App\Infrastructure\Persistence\Eloquent\Models\EventModel;
use DateTimeImmutable;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Modules\Tournaments\Domain\Entities\Tournament;
use Modules\Tournaments\Domain\Enums\ResultReporting;
use Modules\Tournaments\Domain\Enums\TournamentStatus;
use Modules\Tournaments\Domain\Exceptions\TournamentNotFoundException;
use Modules\Tournaments\Domain\Repositories\TournamentRepositoryInterface;
use Modules\Tournaments\Domain\ValueObjects\TournamentId;
use Modules\Tournaments\Infrastructure\Persistence\Eloquent\Models\TournamentModel;
use Modules\Tournaments\Infrastructure\Persistence\Eloquent\Repositories\EloquentTournamentRepository;
use Tests\TestCase;

final class EloquentTournamentRepositoryTest extends TestCase
{
    use RefreshDatabase;

    private EloquentTournamentRepository $repository;

    protected function setUp(): void
    {
        parent::setUp();
        $this->repository = new EloquentTournamentRepository();
    }

    public function test_it_implements_tournament_repository_interface(): void
    {
        $this->assertInstanceOf(TournamentRepositoryInterface::class, $this->repository);
    }

    public function test_it_saves_new_tournament(): void
    {
        $event = EventModel::factory()->create();
        $id = TournamentId::generate();

        $tournament = new Tournament(
            id: $id,
            eventId: $event->id,
            name: 'Test Tournament',
            slug: 'test-tournament',
            status: TournamentStatus::Draft,
            scoreWeights: [],
            tiebreakers: [],
            resultReporting: ResultReporting::AdminOnly,
            description: 'A test tournament',
            maxRounds: 5,
            maxParticipants: 16,
            minParticipants: 4,
        );

        $this->repository->save($tournament);

        $this->assertDatabaseHas('tournaments_tournaments', [
            'id' => $id->value,
            'event_id' => $event->id,
            'name' => 'Test Tournament',
            'slug' => 'test-tournament',
            'status' => 'draft',
            'description' => 'A test tournament',
            'max_rounds' => 5,
            'max_participants' => 16,
            'min_participants' => 4,
            'result_reporting' => 'admin_only',
        ]);
    }

    public function test_it_updates_existing_tournament(): void
    {
        $event = EventModel::factory()->create();
        $model = TournamentModel::create([
            'id' => $id = TournamentId::generate()->value,
            'event_id' => $event->id,
            'name' => 'Original Name',
            'slug' => 'original-name',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        $tournament = new Tournament(
            id: TournamentId::fromString($id),
            eventId: $event->id,
            name: 'Updated Name',
            slug: 'updated-name',
            status: TournamentStatus::RegistrationOpen,
            scoreWeights: [],
            tiebreakers: [],
            resultReporting: ResultReporting::PlayersTrusted,
        );

        $this->repository->save($tournament);

        // Note: The slug is auto-generated by HasSlug trait when name changes
        // It includes a UUID suffix, so we check other fields and slug starts with expected base
        $this->assertDatabaseHas('tournaments_tournaments', [
            'id' => $id,
            'name' => 'Updated Name',
            'status' => 'registration_open',
            'result_reporting' => 'players_trusted',
        ]);

        // Verify slug was updated (starts with 'updated-name')
        $updatedModel = TournamentModel::find($id);
        $this->assertStringStartsWith('updated-name', $updatedModel->slug);

        $this->assertDatabaseMissing('tournaments_tournaments', [
            'name' => 'Original Name',
        ]);
    }

    public function test_it_finds_by_id(): void
    {
        $event = EventModel::factory()->create();
        $model = TournamentModel::create([
            'id' => $id = TournamentId::generate()->value,
            'event_id' => $event->id,
            'name' => 'Test Tournament',
            'slug' => 'test-tournament',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
            'max_rounds' => 4,
        ]);

        $tournament = $this->repository->find(TournamentId::fromString($id));

        $this->assertNotNull($tournament);
        $this->assertEquals($id, $tournament->id()->value);
        $this->assertEquals('Test Tournament', $tournament->name());
        $this->assertEquals('test-tournament', $tournament->slug());
        $this->assertEquals(TournamentStatus::Draft, $tournament->status());
        $this->assertEquals(ResultReporting::AdminOnly, $tournament->resultReporting());
        $this->assertCount(0, $tournament->scoreWeights());
        $this->assertCount(0, $tournament->tiebreakers());
        $this->assertEquals(4, $tournament->maxRounds());
    }

    public function test_it_returns_null_when_not_found(): void
    {
        $tournament = $this->repository->find(TournamentId::generate());

        $this->assertNull($tournament);
    }

    public function test_find_or_fail_throws_exception_when_not_found(): void
    {
        $this->expectException(TournamentNotFoundException::class);

        $this->repository->findOrFail(TournamentId::generate());
    }

    public function test_it_finds_by_slug(): void
    {
        $event = EventModel::factory()->create();
        TournamentModel::create([
            'id' => $id = TournamentId::generate()->value,
            'event_id' => $event->id,
            'name' => 'Warhammer Tournament',
            'slug' => 'warhammer-tournament',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        $tournament = $this->repository->findBySlug('warhammer-tournament');

        $this->assertNotNull($tournament);
        $this->assertEquals($id, $tournament->id()->value);
        $this->assertEquals('Warhammer Tournament', $tournament->name());
    }

    public function test_it_returns_null_when_slug_not_found(): void
    {
        $tournament = $this->repository->findBySlug('non-existent-slug');

        $this->assertNull($tournament);
    }

    public function test_it_finds_by_event_id(): void
    {
        $event = EventModel::factory()->create();
        TournamentModel::create([
            'id' => $id = TournamentId::generate()->value,
            'event_id' => $event->id,
            'name' => 'Event Tournament',
            'slug' => 'event-tournament',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        $tournament = $this->repository->findByEventId($event->id);

        $this->assertNotNull($tournament);
        $this->assertEquals($id, $tournament->id()->value);
        $this->assertEquals($event->id, $tournament->eventId());
    }

    public function test_it_returns_null_when_event_id_not_found(): void
    {
        $tournament = $this->repository->findByEventId('non-existent-event-id');

        $this->assertNull($tournament);
    }

    public function test_it_finds_by_status(): void
    {
        $events = EventModel::factory()->count(5)->create();

        TournamentModel::create([
            'event_id' => $events[0]->id,
            'name' => 'Draft Tournament 1',
            'slug' => 'draft-tournament-1',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        TournamentModel::create([
            'event_id' => $events[1]->id,
            'name' => 'Draft Tournament 2',
            'slug' => 'draft-tournament-2',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        TournamentModel::create([
            'event_id' => $events[2]->id,
            'name' => 'Open Tournament',
            'slug' => 'open-tournament',
            'status' => 'registration_open',
            'result_reporting' => 'admin_only',
        ]);

        $draftTournaments = $this->repository->findByStatus(TournamentStatus::Draft);

        $this->assertCount(2, $draftTournaments);
        foreach ($draftTournaments as $tournament) {
            $this->assertEquals(TournamentStatus::Draft, $tournament->status());
        }
    }

    public function test_it_deletes_tournament(): void
    {
        $event = EventModel::factory()->create();
        $model = TournamentModel::create([
            'id' => $id = TournamentId::generate()->value,
            'event_id' => $event->id,
            'name' => 'Tournament To Delete',
            'slug' => 'tournament-to-delete',
            'status' => 'draft',
            'result_reporting' => 'admin_only',
        ]);

        $this->assertDatabaseHas('tournaments_tournaments', ['id' => $id]);

        $this->repository->delete(TournamentId::fromString($id));

        $this->assertDatabaseMissing('tournaments_tournaments', ['id' => $id]);
    }

    public function test_it_returns_all_tournaments(): void
    {
        $events = EventModel::factory()->count(3)->create();

        foreach ($events as $i => $event) {
            TournamentModel::create([
                'event_id' => $event->id,
                'name' => "Tournament {$i}",
                'slug' => "tournament-{$i}",
                'status' => 'draft',
                'result_reporting' => 'admin_only',
            ]);
        }

        $tournaments = $this->repository->all();

        $this->assertCount(3, $tournaments);
    }

    public function test_it_handles_nullable_fields_correctly(): void
    {
        $event = EventModel::factory()->create();
        $id = TournamentId::generate();

        $tournament = new Tournament(
            id: $id,
            eventId: $event->id,
            name: 'Minimal Tournament',
            slug: 'minimal-tournament',
            status: TournamentStatus::Draft,
            scoreWeights: [],
            tiebreakers: [],
            resultReporting: ResultReporting::AdminOnly,
            description: null,
            maxRounds: null,
            maxParticipants: null,
        );

        $this->repository->save($tournament);

        $retrieved = $this->repository->find($id);

        $this->assertNotNull($retrieved);
        $this->assertNull($retrieved->description());
        $this->assertNull($retrieved->maxRounds());
        $this->assertNull($retrieved->maxParticipants());
    }

    public function test_it_handles_allowed_roles_correctly(): void
    {
        $event = EventModel::factory()->create();
        $id = TournamentId::generate();

        $tournament = new Tournament(
            id: $id,
            eventId: $event->id,
            name: 'Role Restricted Tournament',
            slug: 'role-restricted',
            status: TournamentStatus::Draft,
            scoreWeights: [],
            tiebreakers: [],
            resultReporting: ResultReporting::AdminOnly,
            allowedRoles: ['admin', 'member'],
        );

        $this->repository->save($tournament);

        $retrieved = $this->repository->find($id);

        $this->assertNotNull($retrieved);
        $this->assertEquals(['admin', 'member'], $retrieved->allowedRoles());
    }

    public function test_it_handles_date_fields_correctly(): void
    {
        $event = EventModel::factory()->create();
        $id = TournamentId::generate();
        $registrationOpens = new DateTimeImmutable('2026-02-01 10:00:00');
        $registrationCloses = new DateTimeImmutable('2026-02-15 18:00:00');

        $tournament = new Tournament(
            id: $id,
            eventId: $event->id,
            name: 'Dated Tournament',
            slug: 'dated-tournament',
            status: TournamentStatus::Draft,
            scoreWeights: [],
            tiebreakers: [],
            resultReporting: ResultReporting::AdminOnly,
            registrationOpensAt: $registrationOpens,
            registrationClosesAt: $registrationCloses,
        );

        $this->repository->save($tournament);

        $retrieved = $this->repository->find($id);

        $this->assertNotNull($retrieved);
        $this->assertNotNull($retrieved->registrationOpensAt());
        $this->assertNotNull($retrieved->registrationClosesAt());
        $this->assertEquals('2026-02-01', $retrieved->registrationOpensAt()->format('Y-m-d'));
        $this->assertEquals('2026-02-15', $retrieved->registrationClosesAt()->format('Y-m-d'));
    }
}
